# Generated by Django 4.2.5 on 2024-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]