# Generated by Django 4.2.5 on 2024-02-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosk", "0003_remove_order_optionid_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]