# Generated by Django 4.2.10 on 2024-02-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_remove_option_quantity_alter_cart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuImgUrl',
        ),
        migrations.AddField(
            model_name='menu',
            name='menuImg',
            field=models.ImageField(blank=True, null=True, upload_to='kiosk/menu_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='option',
            name='button',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='option',
            name='menuId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncontent',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optioncontent',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
